### ISSUE TITLE
very new HA user cant seem to set the correct path!

### ISSUE THREAD

**Issue by GngrClapz** [exetico/Home-Assistant_Attachments-for-YouTube#1]
Hello all im extremely new to HA but im trying to learn the best i can and install FloorPlan but in following his video i get to the part where i should see the floorplan after entering the code and its not there i change the paths and still cant seem to get it to work! any ideas? if its easier for any  of you id be forever greatful to chat on discord for im sure ill need more help! thanks in advance! Gngr#2878

**Comment by exetico** [comment]
Hi GngrClapz

You need to provide us with some information of what you have done in your system, provide both code and screenshot(s). Remeber to format the code properly with something like this, too:
<img width="92" alt="image" src="https://github.com/exetico/Home-Assistant_Attachments-for-YouTube/assets/3549445/69050b9c-68ce-4d22-9cb1-5b221390e67a">

And oh :) You used my YouTube-repo, which is cool, but I'd kindly ask you to head over to:
https://github.com/ExperienceLovelace/ha-floorplan/discussions 

Before you post in the discussions area, consider to search a bit. There's plenty of questions raised with people struggling to get things working in the initial steps. If you're still fighting with your machine and HA, please provide as much details as possible, in a new [discussion](https://github.com/ExperienceLovelace/ha-floorplan/discussions) 😃 .

Thank you, and I'll see you there.
