### ISSUE TITLE
home_simple

### ISSUE THREAD

**Issue by sergentum** [exetico/Home-Assistant_Attachments-for-YouTube#2]
I'm trying to follow first video - add home_simple to my HA instance.
HACS is installed, floorplan\home_simple\* with content uploaded.
And I get next error: Custom element doesn't exist: floorplan-card.
Any advices?

**Comment by exetico** [comment]
Hi, I'm sorry for the late reply. I can see you've closed the issue, so please share your solution here, too. 
With that said, next time feel free to contact us here:

https://github.com/ExperienceLovelace/ha-floorplan/discussions
